# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/XML-Atom-FromOWL/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires
		"Data::UUID",
		"XML::LibXML 1.94",
		"namespace::clean",
		"RDF::TrineX::Functions",
		"XML::Atom".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/XML/Atom/FromOWL.pm" .

